FROM postgres:latest


# Set time zone to Hong Kong and locale to en_US.UTF-8
RUN apt-get update && apt-get install -y locales tzdata && \
    ln -fs /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    locale-gen en_US.UTF-8

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV TZ=Asia/Hong_Kong

EXPOSE 5432

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres
ENV PGDATA=/var/lib/postgresql/data

# Copy the initialization script to the PostgreSQL init directory
COPY init.sql /docker-entrypoint-initdb.d/

# Create log directory with correct permissions
RUN mkdir -p /var/log/postgresql && \
    chown -R postgres:postgres /var/log/postgresql

CMD ["postgres", "-c", "logging_collector=on", "-c", "log_destination=stderr", "-c", "log_directory=/var/log/postgresql", "-c", "log_filename=postgresql.log"]
